version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
    steps:
      - checkout
      - run:
          name: update Ubuntu
          command: sudo apt update
      - run:
          name: install suite-sparse
          command: sudo apt -y install libsuitesparse-dev
      - run:
          name: install hdf5
          command: sudo apt -y install hdf5-tools
      - run:
          name: install gcc@7
          command: sudo apt -y install gcc-7
      - run:
          name: set up variables
          command: export HDF5_USE_FILE_LOCKING="FALSE" && export C_INCLUDE_PATH="/usr/local/include" && export LIBRARY_PATH="/usr/local/lib"
