version: 2
jobs:
  build:
    working_directory: ~/MDOODZ
    docker:
      - image: cimg/node:14.10.1
        environment:
          HDF5_USE_FILE_LOCKING: FALSE
          C_INCLUDE_PATH: /usr/local/include:/usr/include/hdf5/serial:/usr/include/suitesparse
          LIBRARY_PATH: /usr/lib/:/usr/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu/hdf5/serial
    steps:
      - checkout
      - run:
          name: update Ubuntu
          command: sudo apt update
      - run:
          name: install gcc@7
          command: sudo apt -y install gcc-7
      - run:
          name: install suite-sparse
          command: sudo apt -y install libsuitesparse-dev
      - run:
          name: install hdf5
          command: sudo apt -y install libhdf5-serial-dev
      - run:
          name: prepare makefiile
          command: mv SOURCE/Makefiles/makefile_ubuntu_ci SOURCE/makefile
      - run:
          name: build RiftingPaulineMD6
          command: cd SOURCE/ && make all MODEL=RiftingPaulineMD6 OPT=yes MKL=yes
      - run:
          name: build RiftingPaulineMD6 2
          command: cd SOURCE/ && ./Doodzi_RiftingPaulineMD6 RiftingPaulineMD6.txt
