version: 2
jobs:
  build:
    working_directory: ~/SOURCE
    steps:
      - checkout
      - run:
          name: update Ubuntu
          command: sudo apt update
      - run:
          name: install suite-sparse
          command: sudo apt -y install suite-sparse
      -run:
          name: install hdf5
          command: sudo apt -y install hdf5
      -run:
          name: install gcc@7
          command: sudo apt -y install gcc@7
      -run:
          name: set up variables
          command: ./env.sh apt